Little.Concur.Site/Models/AjaxActionModel.cs
namespace Little.Concur.Site.Models
{
    public class AjaxActionModel
    {
        public bool success { get; set; }
        public string message { get; set; }
        public string successurl { get; set; }
        public bool islinkonly { get; set; }
        public object data { get; set; }
        //public IEnumerable<AjaxError> errors { get; set; } // message, field
    }
}

Little.Concur.Site/Controllers/API/PaymentBatchAPIController.cs
using System.Threading.Tasks;
using System.Web.Http;
using Little.Concur.PaymentBatch.Core;
using Little.Concur.Site.Models;
using Serilog;

namespace Little.Concur.Site.Controllers.API
{
    public class PaymentBatchAPIController : ApiController
    {
        private readonly ILogger _log;
        private readonly ConcurPaymentBatchIntegrator _integrator;

        public PaymentBatchAPIController(IConcurPaymentBatchIntegrator integrator) : base()
        {
            _integrator = (ConcurPaymentBatchIntegrator)integrator;
            _log = Log.ForContext<PaymentBatchAPIController>();
        }

        [HttpGet]
        [ActionName("ForceRefresh")]
        public async Task<AjaxActionModel> RefreshStagingBatchSummaryAsync()
        {
            await _integrator.RefreshStagingBatchSummaryAsync();
            return new AjaxActionModel
            {
                success = true,
                successurl = "/PaymentBatch"
            };
        }

        [HttpGet]
        [ActionName("CloseConcurBatch")]
        public async Task<AjaxActionModel> CloseConcurBatchAsync(string id)
        {
            if (id.IsEmpty())
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = "Batch ID missing"
                };
            }
            var batch = await _integrator.GetStagingBatchSummaryAsync(id);
            if (batch == null)
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = $"Unable to find record for batch id: {id}"
                };
            }
            var filePath = _integrator.CloseAndSaveBatchFile(batch);
            if (filePath.IsEmpty())
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = $"Unable to save file for batch id: {id}"
                };
            }
            return new AjaxActionModel
            {
                success = true
            };
        }

        [HttpGet]
        [ActionName("Stage")]
        public async Task<AjaxActionModel> Stage(string id)
        {
            if (id.IsEmpty())
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = "Batch ID missing"
                };
            }
            var batch = await _integrator.GetStagingBatchSummaryAsync(id);
            if (batch == null)
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = $"Unable to find record for batch id: {id}"
                };
            }
            var count = await _integrator.StageAsync(batch);
            return new AjaxActionModel
            {
                success = count > 0,
                message = count <= 0 ? "Unable to stage journal entries" : $"Staged {count} journal entries"
            };
        }

        [HttpGet]
        [ActionName("SaveToBst")]
        public async Task<AjaxActionModel> SaveToBst(string id)
        {
            if (id.IsEmpty())
            {
                return new AjaxActionModel
                {
                    success = false,
                    message = "Batch ID missing"
                };
            }
            await _integrator.SaveBatchToBst(id);
            return new AjaxActionModel
            {
                success = true
            };
        }
    }
}

Little.Concur.Site/Controllers/API/PingController.cs
using System;
using System.Web.Http;

namespace Little.Concur.Site.Controllers.API
{
    public class PingController : ApiController
    {
        public PingController() : base()
        {
        }

        // GET: api/PingAPI
        public DateTimeOffset Get()
        {
            return DateTimeOffset.Now;
        }
    }
}

Little.Concur.Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Little.Concur.Site.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Little.Concur.Site/Controllers/PaymentBatchController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Little.Concur.PaymentBatch.Core;
using Serilog;

namespace Little.Concur.Site.Controllers
{
    public class PaymentBatchController : Controller
    {
        private readonly ILogger _log;
        private readonly ConcurPaymentBatchIntegrator _integrator;

        public PaymentBatchController(IConcurPaymentBatchIntegrator integrator) : base()
        {
            _integrator = (ConcurPaymentBatchIntegrator)integrator;
            _log = Log.ForContext<PaymentBatchController>();
        }

        // GET: PaymentBatch
        public async Task<ActionResult> Index()
        {
            var model = await _integrator.GetStagingBatchSummariesAsync();
            return View("index", model);
        }

        // GET: PaymentBatch/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var model = await _integrator.GetStagingBatchSummaryAsync(id);
            return View("details", model);
        }
    }
}

Little.Concur.Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Little-Concur Integrator</h1>
    <p>
        @Html.ActionLink("Payment Batches", "Index", "PaymentBatch", null, new { @class = "btn btn-primary btn-lg" })
    </p>
</div>

Little.Concur.Site/Views/PaymentBatch/details.cshtml
@model Little.Concur.PaymentBatch.Core.Data.StagingBatchSummary
@{
    ViewBag.Title = "Payment Batch Details";
}
<h1>Payment Batch Details</h1>
<div class="BatchSummary" data-batchid="@Model.Id">
    <button type="button" class="btn btn-sm btn-primary CloseConcurBatch">
        <i class="fa fa-gavel"></i> Close in Concur
    </button>
    @if (Model.IsFileLocal)
    {
        <a class="btn btn-sm btn-info" href="~/Content/batches/@Model.FileName"><i class="fa fa-paperclip"></i> Raw CSV</a>
        <button type="button" class="btn btn-sm btn-primary StageBatch">
            <i class="fa fa-magic"></i> Stage
        </button>
        <button type="button" class="btn btn-sm btn-danger SaveBatchBst">
            <i class="fa fa-floppy-o"></i> BST
        </button>
    }
</div>
<div class="row">
    <div class="col">
    <dl>
        <dt>Name</dt>
        <dd>@Model.Name</dd>

        <dt>Concur Status</dt>
        <dd>@(Model.IsClosed ? "Closed" : "Open")</dd>

        <dt>Type</dt>
        <dd>@Model.Type</dd>
    </dl>
    </div>
    <div class="col">
        <dl>
            <dt>Payment Method</dt>
            <dd>@Model.PaymentMethod</dd>

            <dt>Amount</dt>
            <dd>$@String.Format("{0:#,##0.00}", Model.Amount)</dd>

            <dt>Documents</dt>
            <dd>@Model.Count</dd>
        </dl>
    </div>
</div>
<div>
    <table class='table table-striped datatable'>
        <thead>
            <tr>
                <th>Batch Key</th>
                <th>Seq #</th>
                <th>Line #</th>
                <th>Period End</th>
                <th class="text-right">Debit</th>
                <th class="text-right">Credit</th>
                <th>Staged</th>
                <th>Completed</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in Model.StagedEntries)
            {
            <tr>
                <td>@entry.batch_skey</td>
                <td>@entry.seq_nbr</td>
                <td>@entry.line_nbr</td>
                <td class="text-nowrap">@(entry.per_end_date.HasValue ? entry.per_end_date.Value.ToString("yyyy-MM-dd") : "")</td>
                <td class="text-right">$@String.Format("{0:#,##0.00}", entry.db_amt_ac)</td>
                <td class="text-right">$@String.Format("{0:#,##0.00}", entry.cr_amt_ac)</td>
                <td class="text-nowrap">@entry.Staged.ToString("yyyy-MM-dd")</td>
                <td class="text-nowrap">@(entry.Completed.HasValue ? entry.Completed.Value.ToString("yyyy-MM-dd") : "")</td>
            </tr>
            }
        </tbody>
    </table>
</div>

Little.Concur.Site/Views/PaymentBatch/index.cshtml
@model System.Collections.Generic.List<Little.Concur.PaymentBatch.Core.Data.StagingBatchSummary>
@{
    ViewBag.Title = "Payment Batches";
}
<h1>Payment Batches</h1>
<p class="mb-1">Last Concur refresh on @Model.Max(x => x.Retrieved) (will only update if data changes)</p>
<div class="mb-3">
    <button type="button" class="btn btn-sm btn-primary ForceRefresh">
        <i class="fa fa-refresh" aria-hidden="true"></i> Refresh from Concur
    </button>
</div>
<div>
    <table class='table table-striped datatable'>
        <thead>
            <tr>
                <th>Name</th>
                <th class="text-right">Total</th>
                <th class="text-right">Count</th>
                <th>Status</th>
                <th>Type</th>
                <th>Payment Method</th>
                <th>Staged Entries</th>
                <th>Completed Entries</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var batch in Model)
            {
            <tr class="BatchSummary" data-batchid="@batch.Id">
                <td>@Html.ActionLink(batch.Name, "Details", "PaymentBatch", new { id = batch.Id }, null)</td>
                <td class="text-right">$@String.Format("{0:#,##0.00}", batch.Amount)</td>
                <td class="text-right">@batch.Count</td>
                <td>@(batch.IsClosed ? "Closed" : "Open")</td>
                <td>@batch.Type</td>
                <td>@batch.PaymentMethod</td>
                <td>@batch.StagedJournalEntryCount</td>
                <td>@batch.CompletedJournalEntryCount</td>
                <td>
                    <button type="button" class="btn btn-sm btn-primary CloseConcurBatch">
                        <i class="fa fa-gavel"></i> Close in Concur
                    </button>
                    @if (batch.IsFileLocal)
        {
            <a class="btn btn-sm btn-info" href="~/Content/batches/@batch.FileName"><i class="fa fa-paperclip"></i> CSV</a>
            <button type="button" class="btn btn-sm btn-primary StageBatch">
                <i class="fa fa-magic"></i> Stage
            </button>
            <button type="button" class="btn btn-sm btn-danger SaveBatchBst">
                <i class="fa fa-floppy-o"></i> BST
            </button>
}
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Little.Concur.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width">
    <title>@ViewBag.Title</title>
    @RenderSection("head", required: false)
    <link rel="stylesheet" href="~/Content/vendor/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/vendor/datatables/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/vendor/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/site.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @Html.ActionLink("Little-Concur Integrator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Payment Batches", "Index", "PaymentBatch", null, new { @class = "nav-link" })
                </li>
            </ul>
            <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
        </div>
    </nav>
    <div class="container body-content">
        <div id="pageError" class="alert alert-danger alert-dismissible" role="alert" style="display: none;"></div>
        <div id="pageMessage" class="alert alert-info alert-dismissible" role="alert" style="display: none;"></div>
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; @DateTime.Now.Year Little Diversified Architectural Consulting
            </p>
        </footer>
    </div>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/popper/popper.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/vendor/datatables/datatables.net/js/jquery.dataTables.js"></script>
    <script src="~/Content/vendor/datatables/datatables.net-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/Content/vendor/jquery-serializejson/jquery.serializejson.js"></script>
    <script src="~/Content/vendor/jsrender/jsrender.js"></script>
    <script src="~/Content/js/site.debug.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>